---
title: "Industry Forecasts"
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
runtime: shiny
resource_files:
- "data/current/Employment for 64 LMO Industries 2000-2024.xlsx"
- data/current/sim_fcasts.csv
- data/current/lmo_employment_previous.xlsx
- data/current/constraint.csv
- out/current/forecasts.csv
- "data/current/2024E_internal industry forecast_group notes - 2024 03 05.xlsx"
- data/current/constraint.xlsx
- data/current/driver_2025_partial.xlsx
---

```{css, echo=FALSE}
.dataTables_scrollBody {
  max-height: none !important;
}
```

```{r setup, include=FALSE}
#' The main challenge here is that data is being drawn in from multiple sources where
#' it is not certain that industry names and codes are consistent between sources... so we use 
#' fuzzyjoins, which necessitates manually verifying that the joins were done correctly.  The
#' file prepared for Stokes is viewed to be the "correct" naming and numbering,
#' and then we impose this naming on last year's forecasts and the driver data to ensure consistency.

# libraries---------------------
library(flexdashboard)
library(tidyverse)
library(readxl)
library(here)
library(janitor)
library(DT)
library(markdown)
library(shinyalert)
library(fuzzyjoin)
library(plotly)
# constants-----------------------------
historic_start <- 2015
historic_end <- 2024
colors <- c("Employment" = "black", "Last Year" = "purple", "New Forecast" = "orange", "Driver Data" = "blue", "Forecast Already" = "red", "CAGR Forecast"="aquamarine", "Sim Forecast"="yellow")

# if forecast table doesn't exist create it.--------------------
if (!file.exists(here("out","current", "forecasts.csv"))) {
  tibble(year= numeric(), value=numeric(), industry = character()) %>%
    write_csv(here("out","current", "forecasts.csv"))
}

# functions------------------
get_cagr <- function(tbbl, start_year, end_year) {
  start_val <- filter(tbbl, year == start_year) %>%
    pull(value)
  end_val <- filter(tbbl, year == end_year) %>%
    pull(value)
  c(start_year, end_year, scales::percent((end_val / start_val)^(1 / (end_year - start_year)) - 1, accuracy = .1))
}

make_forecast <- function(tbbl){
  tbbl <- tbbl%>%
    mutate(year=as.numeric(year))
  last_value <- tbbl%>%
    filter(year==max(year))%>%
    pull(value)
  start_val <- filter(tbbl, year == historic_start) %>%
    pull(value)
  end_val <- filter(tbbl, year == historic_end) %>%
    pull(value)
  historic_cagr <- (end_val / start_val)^(1 / (historic_end - historic_start))
  multiply_last_value_by <- historic_cagr^(1:11)
  year <- (max(tbbl$year)+1):(max(tbbl$year)+11)
  value <- last_value*multiply_last_value_by
  tibble(industry=input$industry, year=year, value=value)
}
# read in the data--------------------------
# this file is treated as having THE correct industry names and codes.
employment <- read_excel(here("data","current","Employment for 64 LMO Industries 2000-2024.xlsx"), 
                         skip = 2, 
                         sheet = "British Columbia")%>%
  pivot_longer(cols=starts_with("2"), names_to="year", values_to = "value")%>%
  rename(industry=contains("industry"),
         code=contains("code"))%>%
  filter(str_detect(code, "ind"))%>%
  group_by(code, industry)%>%
  nest()%>%
  rename(employment=data)

sim_fcast <- read_csv(here("data","current","sim_fcasts.csv"))|>
  rename(value=mean_fcast)

old <- readxl::read_excel(here("data","current","lmo_employment_previous.xlsx"), skip = 3)|>
  janitor::remove_constant()|>
  pivot_longer(cols=-Industry, names_to = "year")%>%
  mutate(year=as.numeric(year))%>%
  clean_names()%>%
  group_by(industry)%>%
  nest()%>%
  rename(old_forecast=data)

#anti_join(employment, old)|>view()
#anti_join(old, employment)|>view()

old_forecast <- old%>%
  stringdist_right_join(employment)%>% #stoke f'd up industry names: manually check the fuzzy join
  ungroup()|>
  select(-employment, -industry.x)%>%
  rename(industry=industry.y)%>%
  filter(!is.na(code))%>%
  unnest(old_forecast)%>%
  unite(industry, code, industry, sep=": ")%>%
  mutate(year=as.numeric(year))
 
forecast_years <- old_forecast %>% # the years to be forecast
  distinct(year) %>%
  pull(year) + 1

driver_data <- read_excel(here("data","current","driver_2025_partial.xlsx"))%>%  
  select(-contains("code"))%>%
  rename(industry=`Ind Des`)%>%
  pivot_longer(cols=-industry, names_to = "year", values_to = "value")%>%
  group_by(industry)%>%
  nest()%>%
  rename(driver_data=data)%>%
  stringdist_right_join(employment)%>% #don't trust industry names: manually check the fuzzy join
  ungroup()|>
  select(-employment, -industry.x)%>%
  rename(industry=industry.y)%>%
  unnest(driver_data)%>%
  unite(industry, code, industry, sep=": ")%>%
  mutate(year=as.numeric(year),
         value=1000*value) 

employment <- employment%>%
  unnest(employment)%>%
  unite(industry, code, industry, sep=": ")%>%
  mutate(year=as.numeric(year))

forecast_already <- read_csv(here("out","current", "forecasts.csv"))%>%
  group_by(industry, year) %>%
  summarize(value = last(value))|> # only the most recent forecast
  mutate(industry=str_sub(industry, end=-3)) #hack to fix extra columns of 1's appended when writing to disk WTF???

constraint <- read_xlsx(here("data","current", "constraint.xlsx"))|>
  filter(year %in% forecast_years[1:5])|>
  select(year, employment)

# preliminary calculations-------------------
industries <- unique(employment$industry) # for the drop down list.
default_industry <- industries[!industries %in% unique(forecast_already$industry)][1] #make the default choice the next industry.
industry_share_last_year <- employment %>% # for keeping track of how much has been forecast relative to constraint.
  filter(year == max(year), industry != "ind00-ALL") %>%
  mutate(
    industry_proportion = value / sum(value),
    industry = industry
  )
if (nrow(forecast_already > 0)) {
  forecasted_industries <- forecast_already %>%
    select(industry) %>%
    distinct() #which industries have we forecast already?
  `Percent Forecasted` <- inner_join(industry_share_last_year, forecasted_industries, by = "industry") %>%
    summarize(industry_proportion = sum(industry_proportion)) %>%
    mutate(industry_proportion = scales::percent(industry_proportion, accuracy = .01)) %>%
    pull() # what share of total employment do the forecast industries make?
  forecasted_by_year <- forecast_already %>%
    filter(year < mean(year)) %>% # only for the first 5 years of forecast
    group_by(year) %>%
    summarize(total = sum(value)) %>% #total employment forecast already.
    inner_join(constraint, by = "year") %>% # the budget constraint (top line employment)
    mutate(
      `#` = nrow(forecasted_industries),
      `%` = `Percent Forecasted`,
      `Forecasts / Constraint` = scales::percent(total / employment, accuracy = .01),
      too=if_else(`Forecasts / Constraint`>`%`,"high","low")
    ) %>%
    select(-total, -employment)
} else {
  forecasted_by_year <- tibble(
    Year = forecast_years[1:5],
    `#` = rep(0, 5),
    `%` = rep(0, 5),
    `Forecasts / Constraint` = rep(0, 5),
    too = rep("early", 5)
  )
}
#get notes from last year-----------------

notes <- read_excel(here("data","current","2024E_internal industry forecast_group notes - 2024 03 05.xlsx"))%>%
  unite(industry, contains("code"), contains("industry"), sep=": ")|>
  select(industry, starts_with("2"))%>%
  stringdist_right_join(employment|>select(industry)|>distinct())|>
  select(starts_with("2"), industry.y)%>%
  rename(industry=industry.y)|>
  pivot_longer(cols=starts_with("2"))%>%
  mutate(value=str_replace_all(value, "-"," "),
         name=str_remove_all(name, "- notes on forecast"))

```

## Inputs {.sidebar}

```{r}
actionButton("reset", "Reset to clear adjustments")
selectInput(
  "industry",
  "Select an Industry",
  industries,
  selected = default_industry
)

selectInput(
  "fcast",
  "Select a forecast to modify",
  c("Last Year","Driver","CAGR Forecast","Sim Forecast"),
  selected = "Last Year"
)

sliderInput("shift", "Shift up or down",
  min = .7, max = 1.3,
  value = 1, step = .01
)
sliderInput("slope", "Change slope",
  min = .95, max = 1.03,
  value = 1, step = .001
)

sliderInput(
  "curvature", "Degree of concavity",
  min = -100, max = 100,
  value = 0, step = 1
)
```


```{r}
actionButton("save", "Write forecast to disk") #disabled for shinyapps.io

sliderInput("adjust_first", paste("Adjust ", forecast_years[1]),
  min = .9, max = 1.2,   value = 1, step = .001
)
sliderInput("adjust_second", paste("Adjust ", forecast_years[2]),
  min = .9, max = 1.2,   value = 1, step = .001
)
sliderInput("adjust_third", paste("Adjust ", forecast_years[3]),
  min = .9, max = 1.2,   value = 1, step = .001
)
sliderInput("adjust_fourth", paste("Adjust ", forecast_years[4]),
  min = .9, max = 1.2,   value = 1, step = .001
)
sliderInput("adjust_fifth", paste("Adjust ", forecast_years[5]),
  min = .9, max = 1.2,
  value = 1, step = .01
)
sliderInput("adjust_sixth", paste("Adjust ", forecast_years[6]),
  min = .9, max = 1.2,   value = 1, step = .001
)
sliderInput("adjust_seventh", paste("Adjust ", forecast_years[7]),
  min = .9, max = 1.2,   value = 1, step = .001
)
sliderInput("adjust_eighth", paste("Adjust ", forecast_years[8]),
  min = .9, max = 1.2,   value = 1, step = .001
)
sliderInput("adjust_ninth", paste("Adjust ", forecast_years[9]),
  min = .9, max = 1.2,   value = 1, step = .001
)
sliderInput("adjust_tenth", paste("Adjust ", forecast_years[10]),
  min = .9, max = 1.2,   value = 1, step = .001
)
sliderInput("adjust_eleventh", paste("Adjust ", forecast_years[11]),
  min = .9, max = 1.2,   value = 1, step = .001
)
observeEvent(input$reset, {
  updateSliderInput(inputId = "shift", value = 1)
  updateSliderInput(inputId = "slope", value = 1)
  updateNumericInput(inputId = "curvature", value = 0)
  updateSliderInput(inputId = "adjust_first", value = 1)
  updateSliderInput(inputId = "adjust_second", value = 1)
  updateSliderInput(inputId = "adjust_third", value = 1)
  updateSliderInput(inputId = "adjust_fourth", value = 1)
  updateSliderInput(inputId = "adjust_fifth", value = 1)
  updateSliderInput(inputId = "adjust_sixth", value = 1)
  updateSliderInput(inputId = "adjust_seventh", value = 1)
  updateSliderInput(inputId = "adjust_eighth", value = 1)
  updateSliderInput(inputId = "adjust_ninth", value = 1)
  updateSliderInput(inputId = "adjust_tenth", value = 1)
  updateSliderInput(inputId = "adjust_eleventh", value = 1)
})
# reactive elements------------------------

reactive_driver <- reactive({
  driver_data %>%
    filter(industry == input$industry)
})

reactive_employment <- reactive({
  employment %>%
    filter(industry == input$industry)
})

reactive_employment_cagr <- reactive({
  get_cagr(reactive_employment(), historic_start, historic_end)
})

reactive_old <- reactive({
  old_forecast %>%
    filter(industry == input$industry)
})

reactive_CAGR_forecast <- reactive({
  make_forecast(reactive_employment())
})

reactive_sim_forecast <- reactive({
  sim_fcast %>%
    filter(industry == input$industry)
})

reactive_old_cagr <- reactive({
  ffy <- get_cagr(reactive_old(), min(forecast_years) - 1, mean(forecast_years) - 1)
  sfy <- get_cagr(reactive_old(), mean(forecast_years) - 1, max(forecast_years) - 1)
  ty <- get_cagr(reactive_old(), min(forecast_years) - 1, max(forecast_years) - 1)
  temp <- t(bind_cols(ffy, sfy, ty))
  colnames(temp) <- c("Start", "End", "CAGR")
  temp
})

#my most terrible function ever------------------

reactive_new <- reactive({
  adjustment_vector <- c(
    input$adjust_first,
    input$adjust_second,
    input$adjust_third,
    input$adjust_fourth,
    input$adjust_fifth,
    input$adjust_sixth,
    input$adjust_seventh,
    input$adjust_eighth,
    input$adjust_ninth,
    input$adjust_tenth,
    input$adjust_eleventh
  )
  adjustments <- tibble(year = forecast_years, 
                        slope = input$slope^(forecast_years - min(forecast_years)),
                        curvature =  case_when(input$curvature==0 ~ 1,
                                               input$curvature>0 ~ (1-(abs(forecast_years-mean(forecast_years))/(101-abs(input$curvature)))^2),
                                               input$curvature<0 ~ ((abs(forecast_years-mean(forecast_years))/(101-abs(input$curvature)))^2+1)),
                        adjustment_vector = adjustment_vector)
  
  case_when(input$fcast=="Last Year" ~ reactive_old() %>%
              mutate(year = year + 1) %>%
              mutate(value = value * input$shift) %>%
              full_join(adjustments) %>%
              mutate(
                value = value * slope,
                value = value * curvature,
                value = round(value * adjustment_vector)
              ) %>%
              select(-slope, -adjustment_vector),
            input$fcast=="Driver" ~ reactive_driver()%>%
              mutate(value = value * input$shift) %>%
              full_join(adjustments) %>%
              mutate(
                value = value * slope,
                value = value * curvature,
                value = round(value * adjustment_vector)
              ) %>%
              select(-slope, -adjustment_vector),
            input$fcast=="CAGR Forecast"~ reactive_CAGR_forecast()%>%
              mutate(value = value * input$shift) %>%
              full_join(adjustments) %>%
              mutate(
                value = value * slope,
                value = value * curvature,
                value = round(value * adjustment_vector)
              ) %>%
              select(-slope, -adjustment_vector),
            input$fcast=="Sim Forecast"~ reactive_sim_forecast()%>%
              mutate(value = value * input$shift) %>%
              full_join(adjustments) %>%
              mutate(
                value = value * slope,
                value = value * curvature,
                value = round(value * adjustment_vector)
              ) %>%
              ungroup()|>
              select(year, value, industry)|>
              as_tibble()
  )
})

# end of ridiculously long function---------------

reactive_new_cagr <- reactive({
  ffy <- get_cagr(reactive_new(), min(forecast_years), mean(forecast_years))
  sfy <- get_cagr(reactive_new(), mean(forecast_years), max(forecast_years))
  ty <- get_cagr(reactive_new(), min(forecast_years), max(forecast_years))
  temp <- t(bind_cols(ffy, sfy, ty))
  colnames(temp) <- c("Start", "End", "CAGR")
  temp %>%
    as_tibble() %>%
    select(CAGR, Start, End)
})

reactive_already <- reactive({
  forecast_already %>%
    filter(industry == input$industry)
})

observeEvent(input$save, {
  write.table(reactive_new(),
    here("out","current", "forecasts.csv"),
    append = TRUE,
    quote = TRUE,
    sep = ",",
    row.names = FALSE,
    col.names = !file.exists(here("out","current", "forecasts.csv"))
  )
})

reactive_notes <- reactive({
  notes %>%
    filter(industry == input$industry)|>
    select(-industry)
})

```

## Row {data-height=700} {.tabset}

### `r reactive({paste0(input$industry, " (CAGR ", paste(reactive_employment_cagr(),collapse=" "), ")")})`

```{r, fig.retina=2}
plotly::renderPlotly({
  plt <- ggplot(mapping=aes(year,value)) +
    geom_line(data = reactive_employment(), mapping = aes(colour = "Employment"), lwd = 1)
  if(nrow(reactive_driver())>1){
    if(is.na(reactive_driver()$value[1])){shinyalert("No driver data yet")}
    plt <- plt+geom_line(data = reactive_driver(), mapping = aes(colour = "Driver Data"), lwd = 2)
  }
  plt <- plt+
    geom_line(data = reactive_CAGR_forecast(), mapping = aes(colour = "CAGR Forecast"), lwd = 2) +
    geom_line(data = reactive_sim_forecast(), mapping = aes(colour = "Sim Forecast"), lwd = 2)+
    geom_line(data = reactive_old(), mapping = aes(colour = "Last Year"), lwd = 1) +
    geom_line(data = reactive_new(), mapping = aes(colour = "New Forecast"), lwd = 1)
    
  if(nrow(reactive_already())>1){
    plt <- plt+geom_line(data = reactive_already(), mapping = aes(colour = "Forecast Already"), lwd = 1)
  }
  plt <- plt+
    scale_color_manual(values = colors) +
    scale_y_continuous(labels = scales::comma) +
    scale_x_continuous(breaks = seq(min(reactive_employment()$year), max(reactive_new()$year),2))+
    labs(x = "", y = "", color = "") +
    theme(text = element_text(size = 20))
  ggplotly(plt)%>%
  layout(legend = list(
      orientation = "h"
    )
  )
})
```

### Previous years' notes

```{r}
renderDT({
  DT::datatable(reactive_notes(), colnames = NULL, rownames = FALSE, options(dom="t"))
})
```

## Row {data-height="300"}

### Last year's forecast

```{r}
renderDT({
  datatable(reactive_old_cagr(),
    options = list(dom = "t"),
    rownames = FALSE
  )
})
```

### `r renderUI({paste("New forecast based on",input$fcast)})`

```{r}
renderDT({
  datatable(reactive_new_cagr(),
    options = list(dom = "t"),
    rownames = FALSE
  )
})
```

### Budget Constraint

```{r}
renderDT({
  datatable(forecasted_by_year,
    options = list(dom = "t"),
    rownames = FALSE
  )
})
```
